name: Deploy Azure Function App

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build project
        run: dotnet build ./src/sas-key-rotation-function/sas-key-rotation-function.csproj --configuration Release

      - name: Publish Function App
        run: dotnet publish ./src/sas-key-rotation-function/sas-key-rotation-function.csproj -c Release -o ./publish

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ed104207-c4eb-4f25-a990-042c30fff04f
          tenant-id: e46b44b0-4a78-4c07-9f82-043e7432a6a8
          subscription-id: f3571bd1-c070-4529-928f-a2ec94b8e961
          auth-type: IDENTITY

      - name: Set active subscription
        run: az account set --subscription f3571bd1-c070-4529-928f-a2ec94b8e961

      - name: Deploy Infrastructure
        run: |
          az deployment group create \
            --name sas-deploy \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file infrastructure/main.bicep

      - name: Deploy Function
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.FUNCTION_APP_NAME }}
          package: './publish'
