name: Build and deploy Azure Function App - sas-key-rotation-function

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_PATH: 'src/sas-key-rotation-function'
  PUBLISH_DIR: '${{ env.PROJECT_PATH }}/publish'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish Azure Function App
        shell: pwsh
        run: |
          dotnet publish ${{ env.PROJECT_PATH }}/sas-key-rotation-function.csproj `
            --configuration Release `
            --output ${{ env.PUBLISH_DIR }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_040BDF6F3EF945F0B917C1A2BA77B33B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_56F9299F20EA4FD99D12AD2995DB984F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E75E82A0A4CD41B5BF3A33B940E9F064 }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'sas-key-rotation-function'
          slot-name: 'Production'
          package: ${{ env.PUBLISH_DIR }}
